services:
  fetch-unity-info:
    build:
      context: .
    volumes:
      - ${GITHUB_WORKSPACE}:${GITHUB_WORKSPACE}
      - ${GITHUB_OUTPUT_DIR}:${GITHUB_OUTPUT_DIR}
    environment:
      - UNITY_PROJECT_PATH
      - GITHUB_WORKSPACE
      - GITHUB_OUTPUT
